// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouteTargetStatus } from "./ModelRouteTargetStatus";

export type ModelRouteTarget = { id: string, providerId: string,
/**
 * Opaque RichCodex account handle; never an upstream provider identity.
 */
accountId: string, upstreamModelId: string, priority: number, status: ModelRouteTargetStatus, };
