// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelRouteTargetInput = {
/**
 * Preserve an existing target by its opaque RichCodex handle. Omit this
 * field to allocate a new target.
 */
id?: string, providerId: string, accountId: string, upstreamModelId: string, };
