// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification emitted when the model list changes semantically.
 *
 * Clients should invalidate cached picker data and refetch `model/list`. The notification does
 * not carry the catalog itself so a missed notification remains recoverable by refetching.
 */
export type ModelListUpdatedNotification = { revision: string, };
