// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRouteTarget } from "./ModelRouteTarget";

export type ModelRoute = { modelTag: string, displayName: string, retired: boolean, semanticModel: string, targets: Array<ModelRouteTarget>, };
