// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderAccountCredentialKind } from "./ProviderAccountCredentialKind";
import type { ProviderAccountStatus } from "./ProviderAccountStatus";

export type ProviderAccount = {
/**
 * Opaque local identifier. This is not the upstream provider account id.
 */
id: string, providerId: string, userLabel: string, credentialKind: ProviderAccountCredentialKind, status: ProviderAccountStatus,
/**
 * Unix timestamp in seconds.
 */
addedAt: number, };
