// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderAccount } from "./ProviderAccount";
import type { ProviderAccountLoginFailure } from "./ProviderAccountLoginFailure";
import type { ProviderAccountLoginStatus } from "./ProviderAccountLoginStatus";

/**
 * Safe projection of a backend-owned login lifecycle.
 */
export type ProviderAccountLogin = { loginId: string, status: ProviderAccountLoginStatus, verificationUrl: string | null, userCode: string | null,
/**
 * Unix timestamp in seconds when the device code expires.
 */
expiresAt: number, failure: ProviderAccountLoginFailure | null, account: ProviderAccount | null, desiredStateRevision: string, catalogRevision: string, };
