// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RichCodexExecutionReceiptNotification = { threadId: string, turnId: string, clientAttemptId: string | null, modelTag: string, resolvedModel: string, providerId: string,
/**
 * Opaque RichCodex-owned account handle, never an upstream account identity.
 */
accountId: string, targetId: string, attempt: number, };
